name: betcontrol
description: "Betcontrol"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.16
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_flavorizr: ^2.2.3
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#1A3B5D"
  background_image: "assets/images/raster/splash/splash_background.png"
  image: "assets/images/raster/splash/splash_foreground.png"
  android_12:
    image: "assets/images/raster/splash/splash_foreground.png"
    color: "#1A3B5D"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/raster/
    - assets/images/onboarding/
    - assets/images/raster/splash/
    - assets/jsons/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/nunito/Nunito-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300

flavorizr:
  flavors:
    prod:
      app:
        name: "BetControl"

      android:
        applicationId: "com.betcontrol"
      ios:
        bundleId: "com.betcontrol"
      macos:
        bundleId: "com.betcontrol"
    uat:
      app:
        name: "BetControl Uat"

      android:
        applicationId: "com.betcontrol.uat"
      ios:
        bundleId: "com.betcontrol.uat"
      macos:
        bundleId: "com.betcontrol.uat"
    dev:
      app:
        name: "BetControl Dev"

      android:
        applicationId: "com.betcontrol.dev"
      ios:
        bundleId: "com.betcontrol.dev"
      macos:
        bundleId: "com.betcontrol.dev"
